// Dumps the full inputSchema + description of the Ambiguous MCP tools the hands
// connector cares about, plus their close relatives, so the argument builders in
// src/connectors/ambiguous.ts can be written against the real contract.
//
// Connects exactly the way src/connectors/ambiguous.ts does (same Client /
// StreamableHTTPClientTransport / Authorization header) and only calls
// tools/list — it never invokes a tool, so it has no side effects in the
// connected Ambiguous workspace. It never prints key material.
//
// Run with: npx tsx scripts/dump-ambiguous-schemas.ts [outputPath]
// (defaults to scripts/ambiguous-schemas.md, relative to the hands/ directory)
import "../src/env.js";

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

type ListedTool = { name: string; description?: string; inputSchema?: unknown };

// Tools we call directly.
const PRIMARY = ["create_task", "create_document", "create_event", "send_message"];

// Close relatives, grouped by the question they answer. Each group is a list of
// regexes matched against the tool name.
const GROUPS: Array<{ title: string; patterns: RegExp[]; limit: number }> = [
  { title: "Task tools", patterns: [/^(get|list|update|duplicate)_tasks?$/, /^bulk_(delete|archive)_tasks$/], limit: 20 },
  { title: "Document tools", patterns: [/^(get|list|update|export)_documents?$/, /^documents_(delete|permanent_delete|restore|trash_list)$/], limit: 20 },
  { title: "Event / calendar tools", patterns: [/^(get|list|update|delete)_events?$/, /^list_calendars$/], limit: 20 },
  { title: "Message / chat tools", patterns: [/^chat_message_(delete|update)$/, /^bulk_delete_messages$/, /^get_channel_messages$/], limit: 20 },
  { title: "Users / members (assignee resolution)", patterns: [/^(list|search|get)_(users?|members?|people|persons?|contacts?)$/, /^whoami$/, /current_user/], limit: 25 },
  { title: "Channels / conversations (message target)", patterns: [/^(list|search)_channels?$/, /^chat_channel_(get|create)$/], limit: 25 },
  { title: "Projects / spaces / folders (parents)", patterns: [/^(list|get|create)_(projects?|folders?)$/, /^get_workspace$/], limit: 25 },
];

function fence(tool: ListedTool | undefined, name: string): string {
  if (!tool) return `### ${name}\n\n_not advertised_\n`;
  const description = tool.description?.trim() || "_(no description)_";
  return [
    `### ${tool.name}`,
    "",
    description,
    "",
    "```json",
    JSON.stringify(tool.inputSchema ?? null, null, 2),
    "```",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const apiKey = process.env.AMBIGUOUS_API_KEY?.trim();
  const mcpUrl = process.env.AMBIGUOUS_MCP_URL || "https://app.ambiguous.ai/mcp";
  if (!apiKey) {
    console.error("[dump-ambiguous-schemas] AMBIGUOUS_API_KEY is not set");
    process.exitCode = 1;
    return;
  }

  const transport = new StreamableHTTPClientTransport(new URL(mcpUrl), {
    requestInit: { headers: { Authorization: `Bearer ${apiKey}` } },
  });
  const client = new Client({ name: "overheard-hands-dump", version: "0.1.0" });

  try {
    await client.connect(transport);
    const tools: ListedTool[] = [];
    let cursor: string | undefined;
    do {
      const page = await client.listTools(cursor ? { cursor } : undefined);
      tools.push(...(page.tools as ListedTool[]));
      cursor = page.nextCursor;
    } while (cursor);

    const byName = new Map(tools.map((tool) => [tool.name, tool]));
    const out: string[] = [];
    out.push("# Ambiguous MCP tool schemas");
    out.push("");
    out.push(`Source: \`${mcpUrl}\` — \`tools/list\` advertised **${tools.length}** tools.`);
    out.push(`Generated by \`scripts/dump-ambiguous-schemas.ts\`. Schemas only; no key material.`);
    out.push("");
    out.push("## Primary tools (called by src/connectors/ambiguous.ts)");
    out.push("");
    for (const name of PRIMARY) out.push(fence(byName.get(name), name));

    for (const group of GROUPS) {
      const matches = tools
        .filter((tool) => !PRIMARY.includes(tool.name) && group.patterns.some((pattern) => pattern.test(tool.name)))
        .sort((left, right) => left.name.localeCompare(right.name));
      out.push(`## ${group.title}`);
      out.push("");
      if (matches.length === 0) {
        out.push("_no advertised tool matched_");
        out.push("");
        continue;
      }
      if (matches.length > group.limit) {
        out.push(`Matched ${matches.length} tools; showing the first ${group.limit}:`);
        out.push("");
        out.push(matches.map((tool) => `\`${tool.name}\``).join(", "));
        out.push("");
      }
      for (const tool of matches.slice(0, group.limit)) out.push(fence(tool, tool.name));
    }

    out.push("## All advertised tool names");
    out.push("");
    out.push("```");
    out.push([...tools].map((tool) => tool.name).sort().join("\n"));
    out.push("```");

    // Written rather than printed so the env loader's startup banner never ends
    // up inside the markdown.
    const target = join(process.cwd(), process.argv[2] || "scripts/ambiguous-schemas.md");
    await writeFile(target, `${out.join("\n")}\n`, "utf8");
    console.info(`[dump-ambiguous-schemas] wrote ${tools.length} advertised tool names and the selected schemas to ${target}`);
  } finally {
    await client.close().catch(() => {});
  }
}

void main();
